# Example workflow for deploying to GKE
# Copy this to your project and customize as needed
# Make sure you have your Kubernetes manifests in the ./k8s directory
# If using Kustomize, ensure you have a kustomization.yaml file

name: Deploy to GKE

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace to deploy to'
        required: false
        default: 'production'
      dry-run:
        description: 'Perform a dry run without applying changes'
        required: false
        default: false

jobs:
  deploy:
    uses: Praxis-Innovations/github-actions/.github/workflows/k8s-deploy.yml@main
    with:
      manifests-path: './k8s'
      namespace: ${{ github.event.inputs.namespace || 'production' }}
      wait-for-rollout: true
      timeout: '300'
      dry-run: ${{ github.event.inputs.dry-run || false }}
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
      GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
