# Example workflow for Next.js projects
# Copy this to your Next.js project and customize as needed

name: Next.js Build and Docker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-docker:
    uses: Praxis-Innovations/github-actions/.github/workflows/reusable-build-docker.yml@main
    with:
      node-version: '18'
      project-type: 'nextjs'
      build-command: 'yarn build'
      test-command: 'yarn test --watchAll=false --coverage --passWithNoTests'
      start-command: 'yarn start'
      build-output-dirs: '.next/,public/'
      dockerfile-path: './Dockerfile.nextjs'
      docker-context: '.'
      registry: 'ghcr.io'
      image-name: 'your-nextjs-app'
      port: '3000'
      yarn-version: '1.x'
      enable-yarn-berry: false
